# Configuration

inherit_mode:
  merge:
    - Exclude

# Cops

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Metrics:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Max: 25

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
