Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
