Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Metrics:
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Max: 25

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
