Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
