Rails:
  Enabled: true

AllCops:
  Exclude:
    - Rakefile
    - bin/*
    - config/boot.rb
    - config/environment.rb
    - config/environments/**/*.rb
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
